# 配置端口
server:
  port: 8089
# 项目名称
spring:
  application:
    name: order-service
  datasource: #数据库地址
    url: jdbc:mysql://127.0.0.1:3306/leyou?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 123456
    rabbitmq: #配置RabbitMQ
      host: 192.168.228.100
      username: leyou
      password: leyou
      virtual-host: /leyou
      template:
        retry:
          enabled: true
          initial-interval: 10000ms
          max-interval: 300000ms
          multiplier: 2
        exchange: ly.item.exchange
      publisher-confirms: true
    redis: # Redis地址
      host: 192.168.228.100
# 配置eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10
# 配置mybatis
mybatis:
  type-aliases-package: com.java.item.pojo
  mapper-locations: mapper/OrderMapper.xml
  configuration:
    map-underscore-to-camel-case: true
# 配置映射
mapper:
  not-empty: false
  identity: mysql
# 配置
ly:
  worker:
    workerId: 1
    datacenterId: 1
  jwt:
    pubKeyPath: D:/tmp/rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称
  pay: # 微信支付中心
    appId: wx8397f8696b538317 # 密锁
    mchId: 1473426802
    key: 4T6m9iK73b0kn9g5v426MKfHQH7X8rKwb # 密锁
    connectTimeoutMs: 5000
    readTimeoutMs: 10000