# 配置端口
server:
  port: 8088
# 服务名称
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.228.100
# 配置eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10
# 配置jwt
ly:
  jwt:
    pubKeyPath: D:/tmp/rsa.pub # 公钥地址
    cookieName: LY_TOKEN # 指定cookie名字，找加密后的token