# 配置端口
server:
  port: 9081
# 服务名称
spring:
  application:
    name: item-service
  datasource: # 数据库数据源
    url: jdbc:mysql://localhost:3306/leyou
    username: root
    password: 123456
  rabbitmq: # 配置RabbitMQ
    host: 192.168.228.100 # 指定IP地址
    username: leyou # 指定用户名和密码
    password: leyou
    virtual-host: /leyou  # 指定虚拟机
    template:
      retry: #
        enabled: true
        initial-interval: 10000ms
        max-interval: 300000ms
        multiplier: 2
      exchange: ly.item.exchange # 定义一个交换机
    publisher-confirms: true # 发消息的确认机制
# 配置eureka和客户端
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
# 设置打印日志
logging:
  level:
    com.java: debug